SET foreign_key_checks = 0;
TRUNCATE `traveldreamdb`.`finalexcursion`;
TRUNCATE `traveldreamdb`.`finalflight`;
TRUNCATE `traveldreamdb`.`finalhotel`;
TRUNCATE `traveldreamdb`.`finalpackage`;
TRUNCATE `traveldreamdb`.`finalpackage_finalproduct`;
TRUNCATE `traveldreamdb`.`finalpackage_product`;
TRUNCATE `traveldreamdb`.`finalproduct`;
TRUNCATE `traveldreamdb`.`idpool`;
TRUNCATE `traveldreamdb`.`idpool_pool`;
TRUNCATE `traveldreamdb`.`package`;
TRUNCATE `traveldreamdb`.`package_product`;
TRUNCATE `traveldreamdb`.`product`;
TRUNCATE `traveldreamdb`.`sharedpackage`;
TRUNCATE `traveldreamdb`.`user_`;
TRUNCATE `traveldreamdb`.`user_group`;
SET foreign_key_checks = 1;